export const ADD_NEW_BANK_LOADING = 'ADD_NEW_BANK_LOADING';
export const ADD_NEW_BANK_SUCCESS = 'ADD_NEW_BANK_SUCCESS';
export const ADD_NEW_BANK_ERROR = 'ADD_NEW_BANK_ERROR';

export const UPDATE_BANK_LOADING = 'UPDATE_BANK_LOADING';
export const UPDATE_BANK_SUCCESS = 'UPDATE_BANK_SUCCESS';
export const UPDATE_BANK_ERROR = 'UPDATE_BANK_ERROR';

export const GET_BANK_ACCOUNTS_LOADING = 'GET_BANK_ACCOUNTS_LOADING';
export const GET_BANK_ACCOUNTS_SUCCESS = 'GET_BANK_ACCOUNTS_SUCCESS';
export const GET_BANK_ACCOUNTS_ERROR = 'GET_BANK_ACCOUNTS_ERROR';

export const FUND_TRANSFER_LOADING = 'FUND_TRANSFER_LOADING';
export const FUND_TRANSFER_SUCCESS = 'FUND_TRANSFER_SUCCESS';
export const FUND_TRANSFER_ERROR = 'FUND_TRANSFER_ERROR';

export const GET_PAYMENT_ACCOUNT_TRANSACTIONS_LOADING = 'GET_PAYMENT_ACCOUNT_TRANSACTIONS_LOADING';
export const GET_PAYMENT_ACCOUNT_TRANSACTIONS_SUCCESS = 'GET_PAYMENT_ACCOUNT_TRANSACTIONS_SUCCESS';
export const GET_PAYMENT_ACCOUNT_TRANSACTIONS_ERROR = 'GET_PAYMENT_ACCOUNT_TRANSACTIONS_ERROR';

export const GET_PAYMENT_ACCOUNT_DETAILS_LOADING = 'GET_PAYMENT_ACCOUNT_DETAILS_LOADING';
export const GET_PAYMENT_ACCOUNT_DETAILS_SUCCESS = 'GET_PAYMENT_ACCOUNT_DETAILS_SUCCESS';
export const GET_PAYMENT_ACCOUNT_DETAILS_ERROR = 'GET_PAYMENT_ACCOUNT_DETAILS_ERROR';
