export const LOADING = 'LOADING';
export const LOADED = 'LOADED';
export const SUCCESS = 'SUCCESS';
export const FAILED = 'FAILED';

export const BVN_VERIFICATION_LOADING = 'BVN_VERIFICATION_LOADING';
export const BVN_VERIFICATION_SUCCESS = 'BVN_VERIFICATION_SUCCESS';
export const BVN_VERIFICATION_ERROR = 'BVN_VERIFICATION_ERROR';

export const NUBAN_VERIFICATION_LOADING = 'NUBAN_VERIFICATION_LOADING';
export const NUBAN_VERIFICATION_SUCCESS = 'NUBAN_VERIFICATION_SUCCESS';
export const NUBAN_VERIFICATION_ERROR = 'NUBAN_VERIFICATION_ERROR';

export const GET_SECRETS_LOADING = 'GET_SECRETS_LOADING';
export const GET_SECRETS_SUCCESS = 'GET_SECRETS_SUCCESS';
export const GET_SECRETS_ERROR = 'GET_SECRETS_ERROR';

export const SUBMIT_SECRET_LOADING = 'SUBMIT_SECRET_LOADING';
export const SUBMIT_SECRET_SUCCESS = 'SUBMIT_SECRET_SUCCESS';
export const SUBMIT_SECRET_ERROR = 'SUBMIT_SECRET_ERROR';

export const GET_BUSINESS_VERTICALS_LOADING = 'GET_BUSINESS_VERTICALS_LOADING';
export const GET_BUSINESS_VERTICALS_SUCCESS = 'GET_BUSINESS_VERTICALS_SUCCESS';
export const GET_BUSINESS_VERTICALS_ERROR = 'GET_BUSINESS_VERTICALS_ERROR';

export const GET_STATES_ERROR = 'GET_STATES_ERROR';
export const GET_STATES_LOADING = 'GET_STATES_LOADING';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';

export const GET_BUSINESS_REGISTRATION_TYPES_ERROR = 'GET_BUSINESS_REGISTRATION_TYPES_ERROR';
export const GET_BUSINESS_REGISTRATION_TYPES_LOADING = 'GET_BUSINESS_REGISTRATION_TYPES_LOADING';
export const GET_BUSINESS_REGISTRATION_TYPES_SUCCESS = 'GET_BUSINESS_REGISTRATION_TYPES_SUCCESS';

export const REGISTER_BUSINESS_LOADING = 'REGISTER_BUSINESS_LOADING';
export const REGISTER_BUSINESS_SUCCESS = 'REGISTER_BUSINESS_SUCCESS';
export const REGISTER_BUSINESS_ERROR = 'REGISTER_BUSINESS_ERROR';

export const FETCH_INVOICES_LOADING = 'FETCH_INVOICES_LOADING';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR';

export const FETCH_EXPENSES_LOADING = 'FETCH_EXPENSES_LOADING';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSES_ERROR = 'FETCH_EXPENSES_ERROR';

export const CREATE_INVOICE_LOADING = 'CREATE_INVOICE_LOADING';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_ERROR = 'CREATE_INVOICE_ERROR';

export const GET_EXPENSE_ITEM_TYPES_LOADING = 'GET_EXPENSE_ITEM_TYPES_LOADING';
export const GET_EXPENSE_ITEM_TYPES_SUCCESS = 'GET_EXPENSE_ITEM_TYPES_SUCCESS';
export const GET_EXPENSE_ITEM_TYPES_ERROR = 'GET_EXPENSE_ITEM_TYPES_ERROR';

export const GET_EXPENSE_GROUPS_LOADING = 'GET_EXPENSE_GROUPS_LOADING';
export const GET_EXPENSE_GROUPS_SUCCESS = 'GET_EXPENSE_GROUPS_SUCCESS';
export const GET_EXPENSE_GROUPS_ERROR = 'GET_EXPENSE_GROUPS_ERROR';

export const CREATE_EXPENSE_ITEM_TYPE_LOADING = 'CREATE_EXPENSE_ITEM_TYPE_LOADING';
export const CREATE_EXPENSE_ITEM_TYPE_SUCCESS = 'CREATE_EXPENSE_ITEM_TYPE_SUCCESS';
export const CREATE_EXPENSE_ITEM_TYPE_ERROR = 'CREATE_EXPENSE_ITEM_TYPE_ERROR';

export const CREATE_EXPENSE_LOADING = 'CREATE_EXPENSE_LOADING';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_ERROR = 'CREATE_EXPENSE_ERROR';

export const GET_EXPENSE_MEASUREMENT_TYPES_LOADING = 'GET_EXPENSE_MEASUREMENT_TYPES_LOADING';
export const GET_EXPENSE_MEASUREMENT_TYPES_SUCCESS = 'GET_EXPENSE_MEASUREMENT_TYPES_SUCCESS';
export const GET_EXPENSE_MEASUREMENT_TYPES_ERROR = 'GET_EXPENSE_MEASUREMENT_TYPES_ERROR';

export const GET_EXPENSE_BUDGET_PERCENTAGE_LOADING = 'GET_EXPENSE_BUDGET_PERCENTAGE_LOADING';
export const GET_EXPENSE_BUDGET_PERCENTAGE_SUCCESS = 'GET_EXPENSE_BUDGET_PERCENTAGE_SUCCESS';
export const GET_EXPENSE_BUDGET_PERCENTAGE_ERROR = 'GET_EXPENSE_BUDGET_PERCENTAGE_ERROR';

export const GET_EXPENSE_DASHBOARD_STATS_LOADING = 'GET_EXPENSE_DASHBOARD_STATS_LOADING';
export const GET_EXPENSE_DASHBOARD_STATS_SUCCESS = 'GET_EXPENSE_DASHBOARD_STATS_SUCCESS';
export const GET_EXPENSE_DASHBOARD_STATS_ERROR = 'GET_EXPENSE_DASHBOARD_STATS_ERROR';

export const RECORD_SALE_LOADING = 'RECORD_SALE_LOADING';
export const RECORD_SALE_SUCCESS = 'RECORD_SALE_SUCCESS';
export const RECORD_SALE_ERROR = 'RECORD_SALE_ERROR';

export const GET_DASHBOARD_SALES_LOADING = 'GET_DASHBOARD_SALES_LOADING';
export const GET_DASHBOARD_SALES_SUCCESS = 'GET_DASHBOARD_SALES_SUCCESS';
export const GET_DASHBOARD_SALES_ERROR = 'GET_DASHBOARD_SALES_ERROR';

export const GET_DASHBOARD_EXPENSE_LOADING = 'GET_DASHBOARD_EXPENSE_LOADING';
export const GET_DASHBOARD_EXPENSE_SUCCESS = 'GET_DASHBOARD_EXPENSE_SUCCESS';
export const GET_DASHBOARD_EXPENSE_ERROR = 'GET_DASHBOARD_EXPENSE_ERROR';

export const GET_OUTSTANDING_ORDERS_LOADING = 'GET_OUTSTANDING_ORDERS_LOADING';
export const GET_OUTSTANDING_ORDERS_SUCCESS = 'GET_OUTSTANDING_ORDERS_SUCCESS';
export const GET_OUTSTANDING_ORDERS_ERROR = 'GET_OUTSTANDING_ORDERS_ERROR';

export const GET_SALES_DASHBOARD_FIGURE_LOADING = 'GET_SALES_DASHBOARD_FIGURE_LOADING';
export const GET_SALES_DASHBOARD_FIGURE_SUCCESS = 'GET_SALES_DASHBOARD_FIGURE_SUCCESS';
export const GET_SALES_DASHBOARD_FIGURE_ERROR = 'GET_SALES_DASHBOARD_FIGURE_ERROR';

export const GET_SALES_LOADING = 'GET_SALES_LOADING';
export const GET_SALES_SUCCESS = 'GET_SALES_SUCCESS';
export const GET_SALES_ERROR = 'GET_SALES_ERROR';

export const GET_MAIN_DASHBOARD_FIGURE_LOADING = 'GET_MAIN_DASHBOARD_FIGURE_LOADING';
export const GET_MAIN_DASHBOARD_FIGURE_SUCCESS = 'GET_MAIN_DASHBOARD_FIGURE_SUCCESS';
export const GET_MAIN_DASHBOARD_FIGURE_ERROR = 'GET_MAIN_DASHBOARD_FIGURE_ERROR';

export const GET_SALE_DETAILS_LOADING = 'GET_SALE_DETAILS_LOADING';
export const GET_SALE_DETAILS_SUCCESS = 'GET_SALE_DETAILS_SUCCESS';
export const GET_SALE_DETAILS_ERROR = 'GET_SALE_DETAILS_ERROR';

export const ADD_SALE_PAYMENT_LOADING = 'ADD_SALE_PAYMENT_LOADING';
export const ADD_SALE_PAYMENT_SUCCESS = 'ADD_SALE_PAYMENT_SUCCESS';
export const ADD_SALE_PAYMENT_ERROR = 'ADD_SALE_PAYMENT_ERROR';

export const GET_PROFIT_AND_LOSS_LOADING = 'GET_PROFIT_AND_LOSS_LOADING';
export const GET_PROFIT_AND_LOSS_SUCCESS = 'GET_PROFIT_AND_LOSS_SUCCESS';
export const GET_PROFIT_AND_LOSS_ERROR = 'GET_PROFIT_AND_LOSS_ERROR';

export const GET_BALANCESHEET_LOADING = 'GET_BALANCESHEET_LOADING';
export const GET_BALANCESHEET_SUCCESS = 'GET_BALANCESHEET_SUCCESS';
export const GET_BALANCESHEET_ERROR = 'GET_BALANCESHEET_ERROR';

export const ADD_EXPENSE_PAYMENT_LOADING = 'ADD_EXPENSE_PAYMENT_LOADING';
export const ADD_EXPENSE_PAYMENT_SUCCESS = 'ADD_EXPENSE_PAYMENT_SUCCESS';
export const ADD_EXPENSE_PAYMENT_ERROR = 'ADD_EXPENSE_PAYMENT_ERROR';

export const GET_EXPENSE_DETAILS_LOADING = 'GET_EXPENSE_DETAILS_LOADING';
export const GET_EXPENSE_DETAILS_SUCCESS = 'GET_EXPENSE_DETAILS_SUCCESS';
export const GET_EXPENSE_DETAILS_ERROR = 'GET_EXPENSE_DETAILS_ERROR';

export const GET_EXPENSE_ITEM_DETAILS_LOADING = 'GET_EXPENSE_ITEM_DETAILS_LOADING';
export const GET_EXPENSE_ITEM_DETAILS_SUCCESS = 'GET_EXPENSE_ITEM_DETAILS_SUCCESS';
export const GET_EXPENSE_ITEM_DETAILS_ERROR = 'GET_EXPENSE_ITEM_DETAILS_ERROR';

export const EDIT_SALE_LOADING = 'EDIT_SALE_LOADING';
export const EDIT_SALE_SUCCESS = 'EDIT_SALE_SUCCESS';
export const EDIT_SALE_ERROR = 'EDIT_SALE_ERROR';

export const SIGNUP_STAGE_TWO = 'business-detail';

export const UPDATE_EXPENSE_LOADING = 'UPDATE_EXPENSE_LOADING';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';
export const UPDATE_EXPENSE_ERROR = 'UPDATE_EXPENSE_ERROR';

export const GET_BAR_CHART_EXPENSE_SUCCESS = 'GET_BAR_CHART_EXPENSE_SUCCESS';
export const GET_BAR_CHART_EXPENSE_ERROR = 'GET_BAR_CHART_EXPENSE_ERROR';
export const GET_BAR_CHART_EXPENSE_LOADING = 'GET_BAR_CHART_EXPENSE_LOADING';

export const GET_STAFF_LIST_FOR_PAYMENT_LOADING = 'GET_STAFF_LIST_FOR_PAYMENT_LOADING';
export const GET_STAFF_LIST_FOR_PAYMENT_SUCCESS = 'GET_STAFF_LIST_FOR_PAYMENT_SUCCESS';
export const GET_STAFF_LIST_FOR_PAYMENT_ERROR = 'GET_STAFF_LIST_FOR_PAYMENT_ERROR';

export const ADD_STAFF_FOR_PAYMENT_LOADING = 'ADD_STAFF_FOR_PAYMENT_LOADING';
export const ADD_STAFF_FOR_PAYMENT_SUCCESS = 'ADD_STAFF_FOR_PAYMENT_SUCCESS';
export const ADD_STAFF_FOR_PAYMENT_ERROR = 'ADD_STAFF_FOR_PAYMENT_ERROR';

export const CALCULATE_TAX_AMOUNT_LOADING = 'CALCULATE_TAX_AMOUNT_LOADING';
export const CALCULATE_TAX_AMOUNT_SUCCESS = 'CALCULATE_TAX_AMOUNT_SUCCESS';
export const CALCULATE_TAX_AMOUNT_ERROR = 'CALCULATE_TAX_AMOUNT_ERROR';

export const CALCULATE_PENSION_AMOUNT_LOADING = 'CALCULATE_PENSION_AMOUNT_LOADING';
export const CALCULATE_PENSION_AMOUNT_SUCCESS = 'CALCULATE_PENSION_AMOUNT_SUCCESS';
export const CALCULATE_PENSION_AMOUNT_ERROR = 'CALCULATE_PENSION_AMOUNT_ERROR';

export const GET_LGAS_ERROR = 'GET_LGAS_ERROR';
export const GET_LGAS_LOADING = 'GET_LGAS_LOADING';
export const GET_LGAS_SUCCESS = 'GET_LGAS_SUCCESS';

export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';
export const GET_COUNTRIES_LOADING = 'GET_COUNTRIES_LOADING';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';

export const MIGRATE_BUSINESS_DATA_LOADING = 'MIGRATE_BUSINESS_DATA_LOADING';
export const MIGRATE_BUSINESS_DATA_SUCCESS = 'MIGRATE_BUSINESS_DATA_SUCCESS';
export const MIGRATE_BUSINESS_DATA_ERROR = 'MIGRATE_BUSINESS_DATA_ERROR';

export const GET_EXPENSE_TAXTYPES_LOADING = 'GET_EXPENSE_TAXTYPES_LOADING';
export const GET_EXPENSE_TAXTYPES_SUCCESS = 'GET_EXPENSE_TAXTYPES_SUCCESS';
export const GET_EXPENSE_TAXTYPES_ERROR = 'GET_EXPENSE_TAXTYPES_ERROR';

export const GET_EXPENSE_PAYMENT_ACCOUNTS_LOADING = 'GET_EXPENSE_PAYMENT_ACCOUNTS_LOADING';
export const GET_EXPENSE_PAYMENT_ACCOUNTS_SUCCESS = 'GET_EXPENSE_PAYMENT_ACCOUNTS_SUCCESS';
export const GET_EXPENSE_PAYMENT_ACCOUNTS_ERROR = 'GET_EXPENSE_PAYMENT_ACCOUNTS_ERROR';

export const UPDATE_EXPENSE_ITEM_TYPE_LOADING = 'UPDATE_EXPENSE_ITEM_TYPE_LOADING';
export const UPDATE_EXPENSE_ITEM_TYPE_SUCCESS = 'UPDATE_EXPENSE_ITEM_TYPE_SUCCESS';
export const UPDATE_EXPENSE_ITEM_TYPE_ERROR = 'UPDATE_EXPENSE_ITEM_TYPE_ERROR';

export const GET_BUSINESS_ASSET_TYPES_LOADING = 'GET_BUSINESS_ASSET_TYPES_LOADING';
export const GET_BUSINESS_ASSET_TYPES_SUCCESS = 'GET_BUSINESS_ASSET_TYPES_SUCCESS';
export const GET_BUSINESS_ASSET_TYPES_ERROR = 'GET_BUSINESS_ASSET_TYPES_ERROR';

export const GET_PAYMENT_CURRENCY_KEY_LIST_LOADING = 'GET_PAYMENT_CURRENCY_KEY_LIST_LOADING';
export const GET_PAYMENT_CURRENCY_KEY_LIST_SUCCESS = 'GET_PAYMENT_CURRENCY_KEY_LIST_SUCCESS';
export const GET_PAYMENT_CURRENCY_KEY_LIST_ERROR = 'GET_PAYMENT_CURRENCY_KEY_LIST_ERROR';

export const GET_SALES_PAYMENT_ACCOUNTS_LOADING = 'GET_SALES_PAYMENT_ACCOUNTS_LOADING';
export const GET_SALES_PAYMENT_ACCOUNTS_SUCCESS = 'GET_SALES_PAYMENT_ACCOUNTS_SUCCESS';
export const GET_SALES_PAYMENT_ACCOUNTS_ERROR = 'GET_SALES_PAYMENT_ACCOUNTS_ERROR';

export const RECORD_ESTIMATE_LOADING = 'RECORD_ESTIMATE_LOADING';
export const RECORD_ESTIMATE_SUCCESS = 'RECORD_ESTIMATE_SUCCESS';
export const RECORD_ESTIMATE_ERROR = 'RECORD_ESTIMATE_ERROR';

export const UPDATE_ESTIMATE_LOADING = 'UPDATE_ESTIMATE_LOADING';
export const UPDATE_ESTIMATE_SUCCESS = 'UPDATE_ESTIMATE_SUCCESS';
export const UPDATE_ESTIMATE_ERROR = 'UPDATE_ESTIMATE_ERROR';

export const PAY_SALARY_COMMISSION_LOADING = 'PAY_SALARY_COMMISSION_LOADING';
export const PAY_SALARY_COMMISSION_SUCCESS = 'PAY_SALARY_COMMISSION_SUCCESS';
export const PAY_SALARY_COMMISSION_ERROR = 'PAY_SALARY_COMMISSION_ERROR';

export const GET_EXPENSE_DASHBOARD_CARDS_INFO_LOADING = 'GET_EXPENSE_DASHBOARD_CARDS_INFO_LOADING';
export const GET_EXPENSE_DASHBOARD_CARDS_INFO_SUCCESS = 'GET_EXPENSE_DASHBOARD_CARDS_INFO_SUCCESS';
export const GET_EXPENSE_DASHBOARD_CARDS_INFO_ERROR = 'GET_EXPENSE_DASHBOARD_CARDS_INFO_ERROR';

export const GET_SALES_DASHBOARD_CARDS_INFO_LOADING = 'GET_SALES_DASHBOARD_CARDS_INFO_LOADING';
export const GET_SALES_DASHBOARD_CARDS_INFO_SUCCESS = 'GET_SALES_DASHBOARD_CARDS_INFO_SUCCESS';
export const GET_SALES_DASHBOARD_CARDS_INFO_ERROR = 'GET_SALES_DASHBOARD_CARDS_INFO_ERROR';

export const GET_ONLY_SALES_LOADING = 'GET_ONLY_SALES_LOADING';
export const GET_ONLY_SALES_SUCCESS = 'GET_ONLY_SALES_SUCCESS';
export const GET_ONLY_SALES_ERROR = 'GET_ONLY_SALES_ERROR';

export const GET_ONLY_EXPENSE_LOADING = 'GET_ONLY_EXPENSE_LOADING';
export const GET_ONLY_EXPENSE_SUCCESS = 'GET_ONLY_EXPENSE_SUCCESS';
export const GET_ONLY_EXPENSE_ERROR = 'GET_ONLY_EXPENSE_ERROR';

export const GET_BUSINESS_DATA_LOADING = 'GET_BUSINESS_DATA_LOADING';
export const GET_BUSINESS_DATA_SUCCESS = 'GET_BUSINESS_DATA_SUCCESS';
export const GET_BUSINESS_DATA_ERROR = 'GET_BUSINESS_DATA_ERROR';

export const GET_BUSINESS_DETAILS_ERROR = 'GET_BUSINESS_DETAILS_ERROR';
export const GET_BUSINESS_DETAILS_SUCCESS = 'GET_BUSINESS_DETAILS_SUCCESS';
export const GET_BUSINESS_DETAILS_LOADING = 'GET_BUSINESS_DETAILS_LOADING';

export const EDIT_BUSINESS_PROFILE_ERROR = 'EDIT_BUSINESS_PROFILE_ERROR';
export const EDIT_BUSINESS_PROFILE_SUCCESS = 'EDIT_BUSINESS_PROFILE_SUCCESS';
export const EDIT_BUSINESS_PROFILE_LOADING = 'EDIT_BUSINESS_PROFILE_LOADING';

export const VERIFY_BUSINESS_PROFILE_UPDATE_ERROR = 'VERIFY_BUSINESS_PROFILE_UPDATE_ERROR';
export const VERIFY_BUSINESS_PROFILE_UPDATE_SUCCESS = 'VERIFY_BUSINESS_PROFILE_UPDATE_SUCCESS';
export const VERIFY_BUSINESS_PROFILE_UPDATE_LOADING = 'VERIFY_BUSINESS_PROFILE_UPDATE_LOADING';

export const CHECK_DATA_MIGRATION_STATUS_LOADING = 'CHECK_DATA_MIGRATION_STATUS_LOADING';
export const CHECK_DATA_MIGRATION_STATUS_SUCCESS = 'CHECK_DATA_MIGRATION_STATUS_SUCCESS';
export const CHECK_DATA_MIGRATION_STATUS_ERROR = 'CHECK_DATA_MIGRATION_STATUS_ERROR';

export const RESET_LOGIN_ERROR_STATE = 'RESET_LOGIN_ERROR_STATE';
export const RESET_SIGNUP_ERROR_STATE = 'RESET_SIGNUP_ERROR_STATE';
export const RESET_EXPENSE_ERROR_STATE = 'RESET_EXPENSE_ERROR_STATE';

export const GENERATE_SALE_TRANSACTION_DOCUMENT_LOADING = 'GENERATE_SALE_TRANSACTION_DOCUMENT_LOADING';
export const GENERATE_SALE_TRANSACTION_DOCUMENT_SUCCESS = 'GENERATE_SALE_TRANSACTION_DOCUMENT_SUCCESS';
export const GENERATE_SALE_TRANSACTION_DOCUMENT_ERROR = 'GENERATE_SALE_TRANSACTION_DOCUMENT_ERROR';

export const SET_PAYMENT_FORM_PREVIOUS_STATE = 'SET_PAYMENT_FORM_PREVIOUS_STATE';

export const GET_DASHBOARD_CREDIT_SALES_LOADING = 'GET_DASHBOARD_CREDIT_SALES_LOADING';
export const GET_DASHBOARD_CREDIT_SALES_SUCCESS = 'GET_DASHBOARD_CREDIT_SALES_SUCCESS';
export const GET_DASHBOARD_CREDIT_SALES_ERROR = 'GET_DASHBOARD_CREDIT_SALES_ERROR';

export const GET_DASHBOARD_CREDIT_PURCHASE_LOADING = 'GET_DASHBOARD_CREDIT_PURCHASE_LOADING';
export const GET_DASHBOARD_CREDIT_PURCHASE_SUCCESS = 'GET_DASHBOARD_CREDIT_PURCHASE_SUCCESS';
export const GET_DASHBOARD_CREDIT_PURCHASE_ERROR = 'GET_DASHBOARD_CREDIT_PURCHASE_ERROR';

export const GET_DASHBOARD_LOAN_DEBTS_LOADING = 'GET_DASHBOARD_LOAN_DEBTS_LOADING';
export const GET_DASHBOARD_LOAN_DEBTS_SUCCESS = 'GET_DASHBOARD_LOAN_DEBTS_SUCCESS';
export const GET_DASHBOARD_LOAN_DEBTS_ERROR = 'GET_DASHBOARD_LOAN_DEBTS_ERROR';

export const UPDATE_EXPENSE_SUPPLY_LOADING = 'UPDATE_EXPENSE_SUPPLY_LOADING';
export const UPDATE_EXPENSE_SUPPLY_SUCCESS = 'UPDATE_EXPENSE_SUPPLY_SUCCESS';
export const UPDATE_EXPENSE_SUPPLY_ERROR = 'UPDATE_EXPENSE_SUPPLY_ERROR';

// TODO extract all sales request to sales-constant file
export const CANCEL_EXPENSE_LOADING = 'CANCEL_EXPENSE_LOADING';
export const CANCEL_EXPENSE_SUCCESS = 'CANCEL_EXPENSE_SUCCESS';
export const CANCEL_EXPENSE_ERROR = 'CANCEL_EXPENSE_ERROR';
