export const REGISTER_CUSTOMER_LOADING = 'REGISTER_CUSTOMER_LOADING';
export const REGISTER_CUSTOMER_SUCCESS = 'REGISTER_CUSTOMER_SUCCESS';
export const REGISTER_CUSTOMER_ERROR = 'REGISTER_CUSTOMER_ERROR';

export const GET_CUSTOMERS_LOADING = 'GET_CUSTOMERS_LOADING';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';
//  bbb
export const UPDATE_CUSTOMER_DETAILS_LOADING = 'UPDATE_CUSTOMER_DETAILS_LOADING';
export const UPDATE_CUSTOMER_DETAILS_SUCCESS = 'UPDATE_CUSTOMER_DETAILS_SUCCESS';
export const UPDATE_CUSTOMER_DETAILS_ERROR = 'UPDATE_CUSTOMER_DETAILS_ERROR';

export const GET_TRANSACTIONS_LOADING = 'GET_TRANSACTIONS_LOADING';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';

export const GET_TRANSACTION_CARD_DETAILS_LOADING = 'GET_TRANSACTION_CARD_DETAILS_LOADING';
export const GET_TRANSACTION_CARD_DETAILS_SUCCESS = 'GET_TRANSACTION_CARD_DETAILS_SUCCESS';
export const GET_TRANSACTION_CARD_DETAILS_ERROR = 'GET_TRANSACTION_CARD_DETAILS_ERROR';
