export const CREATE_DONOR_LOADING = 'CREATE_DONOR_LOADING';
export const CREATE_DONOR_SUCCESS = 'CREATE_DONOR_SUCCESS';
export const CREATE_DONOR_ERROR = 'CREATE_DONOR_ERROR';

export const EDIT_DONOR_LOADING = 'EDIT_DONOR_LOADING';
export const EDIT_DONOR_SUCCESS = 'EDIT_DONOR_SUCCESS';
export const EDIT_DONOR_ERROR = 'EDIT_DONOR_ERROR';

export const GET_DONORS_LOADING = 'GET_DONORS_LOADING';
export const GET_DONORS_SUCCESS = 'GET_DONORS_SUCCESS';
export const GET_DONORS_ERROR = 'GET_DONORS_ERROR';

export const CREATE_DONATION_SCHEME_LOADING = 'CREATE_DONATION_SCHEME_LOADING';
export const CREATE_DONATION_SCHEME_SUCCESS = 'CREATE_DONATION_SCHEME_SUCCESS';
export const CREATE_DONATION_SCHEME_ERROR = 'CREATE_DONATION_SCHEME_ERROR';

export const GET_DONATION_SCHEMES_LOADING = 'GET_DONATION_SCHEMES_LOADING';
export const GET_DONATION_SCHEMES_SUCCESS = 'GET_DONATION_SCHEMES_SUCCESS';
export const GET_DONATION_SCHEMES_ERROR = 'GET_DONATION_SCHEMES_ERROR';

export const GET_DONATION_ITEM_TYPES_LOADING = 'GET_DONATION_ITEM_TYPES_LOADING';
export const GET_DONATION_ITEM_TYPES_SUCCESS = 'GET_DONATION_ITEM_TYPES_SUCCESS';
export const GET_DONATION_ITEM_TYPES_ERROR = 'GET_DONATION_ITEM_TYPES_ERROR';

export const CREATE_DONATION_LOADING = 'CREATE_DONATION_LOADING';
export const CREATE_DONATION_SUCCESS = 'CREATE_DONATION_SUCCESS';
export const CREATE_DONATION_ERROR = 'CREATE_DONATION_ERROR';

export const GET_DONATIONS_LOADING = 'GET_DONATIONS_LOADING';
export const GET_DONATIONS_SUCCESS = 'GET_DONATIONS_SUCCESS';
export const GET_DONATIONS_ERROR = 'GET_DONATIONS_ERROR';

export const UPDATE_DONATION_SCHEME_LOADING = 'UPDATE_DONATION_SCHEME_LOADING';
export const UPDATE_DONATION_SCHEME_SUCCESS = 'UPDATE_DONATION_SCHEME_SUCCESS';
export const UPDATE_DONATION_SCHEME_ERROR = 'UPDATE_DONATION_SCHEME_ERROR';

export const GET_DONATION_DETAILS_LOADING = 'GET_DONATION_DETAILS_LOADING';
export const GET_DONATION_DETAILS_SUCCESS = 'GET_DONATION_DETAILS_SUCCESS';
export const GET_DONATION_DETAILS_ERROR = 'GET_DONATION_DETAILS_ERROR';

export const UPDATE_DONATION_LOADING = 'UPDATE_DONATION_LOADING';
export const UPDATE_DONATION_SUCCESS = 'UPDATE_DONATION_SUCCESS';
export const UPDATE_DONATION_ERROR = 'UPDATE_DONATION_ERROR';

export const GET_DONOR_TRANSACTIONS_LOADING = 'GET_DONOR_TRANSACTIONS_LOADING';
export const GET_DONOR_TRANSACTIONS_SUCCESS = 'GET_DONOR_TRANSACTIONS_SUCCESS';
export const GET_DONOR_TRANSACTIONS_ERROR = 'GET_DONOR_TRANSACTIONS_ERROR';

export const GET_PLEDGES_LOADING = 'GET_PLEDGES_LOADING';
export const GET_PLEDGES_SUCCESS = 'GET_PLEDGES_SUCCESS';
export const GET_PLEDGES_ERROR = 'GET_PLEDGES_ERROR';

export const GET_DONATION_DASHBOARD_STATS_LOADING = 'GET_DONATION_DASHBOARD_STATS_LOADING';
export const GET_DONATION_DASHBOARD_STATS_SUCCESS = 'GET_DONATION_DASHBOARD_STATS_SUCCESS';
export const GET_DONATION_DASHBOARD_STATS_ERROR = 'GET_DONATION_DASHBOARD_STATS_ERROR';

export const GET_DONOR_DONATIONS_LOADING = 'GET_DONOR_DONATIONS_LOADING';
export const GET_DONOR_DONATIONS_SUCCESS = 'GET_DONOR_DONATIONS_SUCCESS';
export const GET_DONOR_DONATIONS_ERROR = 'GET_DONOR_DONATIONS_ERROR';

export const GET_SCHEME_DONATIONS_LOADING = 'GET_SCHEME_DONATIONS_LOADING';
export const GET_SCHEME_DONATIONS_SUCCESS = 'GET_SCHEME_DONATIONS_SUCCESS';
export const GET_SCHEME_DONATIONS_ERROR = 'GET_SCHEME_DONATIONS_ERROR';
