export const GET_ALL_SHAREHOLDERS_LOADING = 'GET_ALL_SHAREHOLDERS_LOADING';
export const GET_ALL_SHAREHOLDERS_SUCCESS = 'GET_ALL_SHAREHOLDERS_SUCCESS';
export const GET_ALL_SHAREHOLDERS_ERROR = 'GET_ALL_SHAREHOLDERS_ERROR';

export const CREATE_NEW_SHAREHOLDER_LOADING = 'CREATE_NEW_SHAREHOLDER_LOADING';
export const CREATE_NEW_SHAREHOLDER_SUCCESS = 'CREATE_NEW_SHAREHOLDER_SUCCESS';
export const CREATE_NEW_SHAREHOLDER_ERROR = 'CREATE_NEW_SHAREHOLDER_ERROR';

export const GET_DASHBOARD_CARD_DETAILS_LOADING = 'GET_DASHBOARD_CARD_DETAILS_LOADING';
export const GET_DASHBOARD_CARD_DETAILS_SUCCESS = 'GET_DASHBOARD_CARD_DETAILS_SUCCESS';
export const GET_DASHBOARD_CARD_DETAILS_ERROR = 'GET_DASHBOARD_CARD_DETAILS_ERROR';

export const ADD_LOAN_LOADING = 'ADD_LOAN_LOADING';
export const ADD_LOAN_SUCCESS = 'ADD_LOAN_SUCCESS';
export const ADD_LOAN_ERROR = 'ADD_LOAN_ERROR';

export const GET_FORMS_OF_CAPTIAL_LOADING = 'GET_FORMS_OF_CAPTIAL_LOADING';
export const GET_FORMS_OF_CAPTIAL_SUCCESS = 'GET_FORMS_OF_CAPTIAL_SUCCESS';
export const GET_FORMS_OF_CAPTIAL_ERROR = 'GET_FORMS_OF_CAPTIAL_ERROR';

export const ADD_CAPITAL_LOADING = 'ADD_CAPITAL_LOADING';
export const ADD_CAPITAL_SUCCESS = 'ADD_CAPITAL_SUCCESS';
export const ADD_CAPITAL_ERROR = 'ADD_CAPITAL_ERROR';

export const GET_ALL_LOANS_LOADING = 'GET_ALL_LOANS_LOADING';
export const GET_ALL_LOANS_SUCCESS = 'GET_ALL_LOANS_SUCCESS';
export const GET_ALL_LOANS_ERROR = 'GET_ALL_LOANS_ERROR';

export const GET_LOAN_DETAILS_CARD_LOADING = 'GET_LOAN_DETAILS_CARD_LOADING';
export const GET_LOAN_DETAILS_CARD_SUCCESS = 'GET_LOAN_DETAILS_CARD_SUCCESS';
export const GET_LOAN_DETAILS_CARD_ERROR = 'GET_LOAN_DETAILS_CARD_ERROR';

export const GET_LOAN_REPAYMENTS_LOADING = 'GET_LOAN_REPAYMENTS_LOADING';
export const GET_LOAN_REPAYMENTS_SUCCESS = 'GET_LOAN_REPAYMENTS_SUCCESS';
export const GET_LOAN_REPAYMENTS_ERROR = 'GET_LOAN_REPAYMENTS_ERROR';

export const ADD_LOAN_REPAYMENT_LOADING = 'ADD_LOAN_REPAYMENT_LOADING';
export const ADD_LOAN_REPAYMENT_SUCCESS = 'ADD_LOAN_REPAYMENT_SUCCESS';
export const ADD_LOAN_REPAYMENT_ERROR = 'ADD_LOAN_REPAYMENT_ERROR';

export const GET_SHAREHOLDER_DETAILS_LOADING = 'GET_SHAREHOLDER_DETAILS_LOADING';
export const GET_SHAREHOLDER_DETAILS_SUCCESS = 'GET_SHAREHOLDER_DETAILS_SUCCESS';
export const GET_SHAREHOLDER_DETAILS_ERROR = 'GET_SHAREHOLDER_DETAILS_ERROR';

export const UPDATE_SHAREHOLDER_DETAILS_LOADING = 'UPDATE_SHAREHOLDER_DETAILS_LOADING';
export const UPDATE_SHAREHOLDER_DETAILS_SUCCESS = 'UPDATE_SHAREHOLDER_DETAILS_SUCCESS';
export const UPDATE_SHAREHOLDER_DETAILS_ERROR = 'UPDATE_SHAREHOLDER_DETAILS_ERROR';

export const GET_CAPITAL_ITEM_TYPES_LOADING = 'GET_CAPITAL_ITEM_TYPES_LOADING';
export const GET_CAPITAL_ITEM_TYPES_SUCCESS = 'GET_CAPITAL_ITEM_TYPES_SUCCESS';
export const GET_CAPITAL_ITEM_TYPES_ERROR = 'GET_CAPITAL_ITEM_TYPES_ERROR';
