export const GET_PAYMENT_TYPES_LOADING = 'GET_PAYMENT_TYPES_LOADING';
export const GET_PAYMENT_TYPES_SUCCESS = 'GET_PAYMENT_TYPES_SUCCESS';
export const GET_PAYMENT_TYPES_ERROR = 'GET_PAYMENT_TYPES_ERROR';

export const UPLOAD_COMPANY_LOGO_LOADING = 'UPLOAD_COMPANY_LOGO_LOADING';
export const UPLOAD_COMPANY_LOGO_SUCCESS = 'UPLOAD_COMPANY_LOGO_SUCCESS';
export const UPLOAD_COMPANY_LOGO_ERROR = 'UPLOAD_COMPANY_LOGO_ERROR';

export const FETCH_COMPANY_LOGO_AND_ADDRESS_LOADING = 'FETCH_COMPANY_LOGO_AND_ADDRESS_LOADING';
export const FETCH_COMPANY_LOGO_AND_ADDRESS_SUCCESS = 'FETCH_COMPANY_LOGO_AND_ADDRESS_SUCCESS';
export const FETCH_COMPANY_LOGO_AND_ADDRESS_ERROR = 'FETCH_COMPANY_LOGO_AND_ADDRESS_ERROR';

export const SET_NAVBAR_BACK_BUTTON_STATE_TO_FALSE = 'SET_NAVBAR_BACK_BUTTON_STATE_TO_FALSE';
export const SET_NAVBAR_BACK_BUTTON_STATE_TO_TRUE = 'SET_NAVBAR_BACK_BUTTON_STATE_TO_TRUE';
export const SET_NAVBAR_CANCEL_BUTTON_STATE_TO_FALSE = 'SET_NAVBAR_CANCEL_BUTTON_STATE_TO_FALSE';

export const SET_NAVBAR_CANCEL_BUTTON_STATE_TO_TRUE = 'SET_NAVBAR_CANCEL_BUTTON_STATE_TO_TRUE';
export const SET_NAVBAR_CART_BUTTON_STATE_TO_FALSE = 'SET_NAVBAR_CART_BUTTON_STATE_TO_FALSE';
export const SET_NAVBAR_CART_BUTTON_STATE_TO_TRUE = 'SET_NAVBAR_CART_BUTTON_STATE_TO_TRUE';

export const UPLOAD_FILE_LOADING = 'UPLOAD_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const SET_FOCUS_ON_INPUT_FIELD = 'SET_FOCUS_ON_INPUT_FIELD';
