export const CREATE_USER_ACCOUNT_LOADING = 'CREATE_USER_ACCOUNT_LOADING';
export const CREATE_USER_ACCOUNT_SUCCESS = 'CREATE_USER_ACCOUNT_SUCCESS';
export const CREATE_USER_ACCOUNT_ERROR = 'CREATE_USER_ACCOUNT_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const VERIFY_USER_ACCOUNT_LOADING = 'VERIFY_USER_ACCOUNT_LOADING';
export const VERIFY_USER_ACCOUNT_SUCCESS = 'VERIFY_USER_ACCOUNT_SUCCESS';
export const VERIFY_USER_ACCOUNT_ERROR = 'VERIFY_USER_ACCOUNT_ERROR';

export const RESET_PASSWORD_EMAIL_LOADING = 'RESET_PASSWORD_EMAIL_LOADING';
export const RESET_PASSWORD_EMAIL_SUCCESS = 'RESET_PASSWORD_EMAIL_SUCCESS';
export const RESET_PASSWORD_EMAIL_ERROR = 'RESET_PASSWORD_EMAIL_ERROR';

export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const SEND_OTP_ERROR = 'SEND_OTP_ERROR';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_LOADING = 'SEND_OTP_LOADING';

export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_LOADING = 'VERIFY_OTP_LOADING';

export const ADD_BUSINESS_USER_ERROR = 'ADD_BUSINESS_USER_ERROR';
export const ADD_BUSINESS_USER_SUCCESS = 'ADD_BUSINESS_USER_SUCCESS';
export const ADD_BUSINESS_USER_LOADING = 'ADD_BUSINESS_USER_LOADING';

export const FETCH_USER_PROFILE_ERROR = 'FETCH_USER_PROFILE_ERROR';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_LOADING = 'FETCH_USER_PROFILE_LOADING';

export const FETCH_BUSINESS_USERS_ERROR = 'FETCH_BUSINESS_USERS_ERROR';
export const FETCH_BUSINESS_USERS_SUCCESS = 'FETCH_BUSINESS_USERS_SUCCESS';
export const FETCH_BUSINESS_USERS_LOADING = 'FETCH_BUSINESS_USERS_LOADING';

export const EDIT_USER_PROFILE_ERROR = 'EDIT_USER_PROFILE_ERROR';
export const EDIT_USER_PROFILE_SUCCESS = 'EDIT_USER_PROFILE_SUCCESS';
export const EDIT_USER_PROFILE_LOADING = 'EDIT_USER_PROFILE_LOADING';

export const VERIFY_USER_PROFILE_UPDATE_ERROR = 'VERIFY_USER_PROFILE_UPDATE_ERROR';
export const VERIFY_USER_PROFILE_UPDATE_SUCCESS = 'VERIFY_USER_PROFILE_UPDATE_SUCCESS';
export const VERIFY_USER_PROFILE_UPDATE_LOADING = 'VERIFY_USER_PROFILE_UPDATE_LOADING';

export const RESET_LOGIN_ERROR_STATE = 'RESET_LOGIN_ERROR_STATE';
export const RESET_SIGNUP_ERROR_STATE = 'RESET_SIGNUP_ERROR_STATE';
export const RESET_EXPENSE_ERROR_STATE = 'RESET_EXPENSE_ERROR_STATE';

export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
