export const GET_INVENTORY_MEASUREMENT_UNITS_LOADING = 'GET_INVENTORY_MEASUREMENT_UNITS_LOADING';
export const GET_INVENTORY_MEASUREMENT_UNITS_SUCCESS = 'GET_INVENTORY_MEASUREMENT_UNITS_SUCCESS';
export const GET_INVENTORY_MEASUREMENT_UNITS_ERROR = 'GET_INVENTORY_MEASUREMENT_UNITS_ERROR';

export const CREATE_STOCK_ITEM_LOADING = 'CREATE_STOCK_ITEM_LOADING';
export const CREATE_STOCK_ITEM_SUCCESS = 'CREATE_STOCK_ITEM_SUCCESS';
export const CREATE_STOCK_ITEM_ERROR = 'CREATE_STOCK_ITEM_ERROR';

export const GET_STOCK_ITEMS_LOADING = 'GET_STOCK_ITEMS_LOADING';
export const GET_STOCK_ITEMS_SUCCESS = 'GET_STOCK_ITEMS_SUCCESS';
export const GET_STOCK_ITEMS_ERROR = 'GET_STOCK_ITEMS_ERROR';

export const GET_INVENTORY_DASHBOARD_CARDS_VALUES_LOADING = 'GET_INVENTORY_DASHBOARD_CARDS_VALUES_LOADING';
export const GET_INVENTORY_DASHBOARD_CARDS_VALUES_SUCCESS = 'GET_INVENTORY_DASHBOARD_CARDS_VALUES_SUCCESS';
export const GET_INVENTORY_DASHBOARD_CARDS_VALUES_ERROR = 'GET_INVENTORY_DASHBOARD_CARDS_VALUES_ERROR';

export const GET_STOCK_ITEM_LEVELS_LOADING = 'GET_STOCK_ITEM_LEVELS_LOADING';
export const GET_STOCK_ITEM_LEVELS_SUCCESS = 'GET_STOCK_ITEM_LEVELS_SUCCESS';
export const GET_STOCK_ITEM_LEVELS_ERROR = 'GET_STOCK_ITEM_LEVELS_ERROR';

export const GET_STOCK_ITEM_DETAILS_CARD_VALUES_LOADING = 'GET_STOCK_ITEM_DETAILS_CARD_VALUES_LOADING';
export const GET_STOCK_ITEM_DETAILS_CARD_VALUES_SUCCESS = 'GET_STOCK_ITEM_DETAILS_CARD_VALUES_SUCCESS';
export const GET_STOCK_ITEM_DETAILS_CARD_VALUES_ERROR = 'GET_STOCK_ITEM_DETAILS_CARD_VALUES_ERROR';

export const GET_SUPPLIERS_LOADING = 'GET_SUPPLIERS_LOADING';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_ERROR = 'GET_SUPPLIERS_ERROR';

export const GET_STOCK_ITEM_ACTIVITIES_LOADING = 'GET_STOCK_ITEM_ACTIVITIES_LOADING';
export const GET_STOCK_ITEM_ACTIVITIES_SUCCESS = 'GET_STOCK_ITEM_ACTIVITIES_SUCCESS';
export const GET_STOCK_ITEM_ACTIVITIES_ERROR = 'GET_STOCK_ITEM_ACTIVITIES_ERROR';

export const GET_STOCK_ITEM_CATEGORIES_LOADING = 'GET_STOCK_ITEM_CATEGORIES_LOADING';
export const GET_STOCK_ITEM_CATEGORIES_SUCCESS = 'GET_STOCK_ITEM_CATEGORIES_SUCCESS';
export const GET_STOCK_ITEM_CATEGORIES_ERROR = 'GET_STOCK_ITEM_CATEGORIES_ERROR';

export const SET_ITEM_REORDER_LEVEL_LOADING = 'SET_ITEM_REORDER_LEVEL_LOADING';
export const SET_ITEM_REORDER_LEVEL_SUCCESS = 'SET_ITEM_REORDER_LEVEL_SUCCESS';
export const SET_ITEM_REORDER_LEVEL_ERROR = 'SET_ITEM_REORDER_LEVEL_ERROR';

export const SET_STOCK_ITEMS_CATEGORY_LOADING = 'SET_STOCK_ITEMS_CATEGORY_LOADING';
export const SET_STOCK_ITEMS_CATEGORY_SUCCESS = 'SET_STOCK_ITEMS_CATEGORY_SUCCESS';
export const SET_STOCK_ITEMS_CATEGORY_ERROR = 'SET_STOCK_ITEMS_CATEGORY_ERROR';
