export const GET_INCOME_TYPES_LOADING = 'INCOME_TYPES_LOADING';
export const GET_INCOME_TYPES_SUCCESS = 'INCOME_TYPES_SUCCESS';
export const GET_INCOME_TYPES_ERROR = 'INCOME_TYPES_ERROR';

export const GET_MEASUREMENT_TYPES_LOADING = 'GET_MEASUREMENT_TYPES_LOADING';
export const GET_MEASUREMENT_TYPES_SUCCESS = 'GET_MEASUREMENT_TYPES_SUCCESS';
export const GET_MEASUREMENT_TYPES_ERROR = 'GET_MEASUREMENT_TYPES_ERROR';

export const REGISTER_PRODUCT_LOADING = 'REGISTER_PRODUCT_LOADING';
export const REGISTER_PRODUCT_SUCCESS = 'REGISTER_PRODUCT_SUCCESS';
export const REGISTER_PRODUCT_ERROR = 'REGISTER_PRODUCT_ERROR';

export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_VAT_OPTIONS_LOADING = 'GET_VAT_OPTIONS_LOADING';
export const GET_VAT_OPTIONS_SUCCESS = 'GET_VAT_OPTIONS_SUCCESS';
export const GET_VAT_OPTIONS_ERROR = 'GET_VAT_OPTIONS_ERROR';

export const GET_INCOME_GROUPS_LOADING = 'GET_INCOME_GROUPS_LOADING';
export const GET_INCOME_GROUPS_SUCCESS = 'GET_INCOME_GROUPS_SUCCESS';
export const GET_INCOME_GROUPS_ERROR = 'GET_INCOME_GROUPS_ERROR';

export const UPDATE_PRODUCT_LOADING = 'UPDATE_PRODUCT_LOADING';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';

export const GET_PRODUCT_TRANSACTIONS_LOADING = 'GET_PRODUCT_TRANSACTIONS_LOADING';
export const GET_PRODUCT_TRANSACTIONS_SUCCESS = 'GET_PRODUCT_TRANSACTIONS_SUCCESS';
export const GET_PRODUCT_TRANSACTIONS_ERROR = 'GET_PRODUCT_TRANSACTIONS_ERROR';
