export const GET_TAX_CONTACT_DETAILS_LOADING = 'GET_TAX_CONTACT_DETAILS_LOADING';
export const GET_TAX_CONTACT_DETAILS_SUCCESS = 'GET_TAX_CONTACT_DETAILS_SUCCESS';
export const GET_TAX_CONTACT_DETAILS_ERROR = 'GET_TAX_CONTACT_DETAILS_ERROR';

export const UPDATE_TAX_CONTACT_DETAILS_LOADING = 'UPDATE_TAX_CONTACT_DETAILS_LOADING';
export const UPDATE_TAX_CONTACT_DETAILS_SUCCESS = 'UPDATE_TAX_CONTACT_DETAILS_SUCCESS';
export const UPDATE_TAX_CONTACT_DETAILS_ERROR = 'UPDATE_TAX_CONTACT_DETAILS_ERROR';

export const GET_TAX_PROFILES_LOADING = 'GET_TAX_PROFILES_LOADING';
export const GET_TAX_PROFILES_SUCCESS = 'GET_TAX_PROFILES_SUCCESS';
export const GET_TAX_PROFILES_ERROR = 'GET_TAX_PROFILES_ERROR';

export const GET_TAX_STATES_LOADING = 'GET_TAX_STATES_LOADING';
export const GET_TAX_STATES_SUCCESS = 'GET_TAX_STATES_SUCCESS';
export const GET_TAX_STATES_ERROR = 'GET_TAX_STATES_ERROR';

export const GET_TAX_STATIONS_LOADING = 'GET_TAX_STATIONS_LOADING';
export const GET_TAX_STATIONS_SUCCESS = 'GET_TAX_STATIONS_SUCCESS';
export const GET_TAX_STATIONS_ERROR = 'GET_TAX_STATIONS_ERROR';

export const CREATE_TAX_PROFILE_LOADING = 'CREATE_TAX_PROFILE_LOADING';
export const CREATE_TAX_PROFILE_SUCCESS = 'CREATE_TAX_PROFILE_SUCCESS';
export const CREATE_TAX_PROFILE_ERROR = 'CREATE_TAX_PROFILE_ERROR';

export const FETCH_TAX_LIABILITIES_LOADING = 'FETCH_TAX_LIABILITIES_LOADING';
export const FETCH_TAX_LIABILITIES_SUCCESS = 'FETCH_TAX_LIABILITIES_SUCCESS';
export const FETCH_TAX_LIABILITIES_ERROR = 'FETCH_TAX_LIABILITIES_ERROR';

export const REMIT_TAX_LIABILITY_LOADING = 'REMIT_TAX_LIABILITY_LOADING';
export const REMIT_TAX_LIABILITY_SUCCESS = 'REMIT_TAX_LIABILITY_SUCCESS';
export const REMIT_TAX_LIABILITY_ERROR = 'REMIT_TAX_LIABILITY_ERROR';

export const GET_TAX_TYPES_LOADING = 'GET_TAX_TYPES_LOADING';
export const GET_TAX_TYPES_SUCCESS = 'GET_TAX_TYPES_SUCCESS';
export const GET_TAX_TYPES_ERROR = 'GET_TAX_TYPES_ERROR';

export const GET_TAX_LIABILITY_TRANSACTIONS_LOADING = 'GET_TAX_LIABILITY_TRANSACTIONS_LOADING';
export const GET_TAX_LIABILITY_TRANSACTIONS_SUCCESS = 'GET_TAX_LIABILITY_TRANSACTIONS_SUCCESS';
export const GET_TAX_LIABILITY_TRANSACTIONS_ERROR = 'GET_TAX_LIABILITY_TRANSACTIONS_ERROR';
