export const GET_VENDORS_LOADING = 'GET_VENDORS_LOADING';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_VENDORS_ERROR = 'GET_VENDORS_ERROR';

export const CREATE_VENDOR_LOADING = 'CREATE_VENDOR_LOADING';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_ERROR = 'CREATE_VENDOR_ERROR';

export const UPDATE_VENDOR_DETAILS_LOADING = 'UPDATE_VENDOR_DETAILS_LOADING';
export const UPDATE_VENDOR_DETAILS_SUCCESS = 'UPDATE_VENDOR_DETAILS_SUCCESS';
export const UPDATE_VENDOR_DETAILS_ERROR = 'UPDATE_VENDOR_DETAILS_ERROR';

export const GET_TRANSACTION_CARD_DETAILS_LOADING = 'GET_TRANSACTION_CARD_DETAILS_LOADING';
export const GET_TRANSACTION_CARD_DETAILS_SUCCESS = 'GET_TRANSACTION_CARD_DETAILS_SUCCESS';
export const GET_TRANSACTION_CARD_DETAILS_ERROR = 'GET_TRANSACTION_CARD_DETAILS_ERROR';

export const GET_TRANSACTIONS_LOADING = 'GET_TRANSACTIONS_LOADING';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';
