import { Currency } from '@/types';

const currencies: Array<Currency> = [
    {
        currencyKey: 4,
        currencyName: 'Afghan Afghani',
        currencyCode: 'AFN',
        currencySymbol: '؋',
    },
    {
        currencyKey: 8,
        currencyName: 'Albanian Lek',
        currencyCode: 'ALL',
        currencySymbol: 'Lek',
    },
    {
        currencyKey: 12,
        currencyName: 'Algerian Dinar',
        currencyCode: 'DZD',
        currencySymbol: 'د.ج.‏',
    },
    {
        currencyKey: 16,
        currencyName: 'US Dollar',
        currencyCode: 'USD',
        currencySymbol: '$',
    },
    {
        currencyKey: 20,
        currencyName: 'Euro',
        currencyCode: 'EUR',
        currencySymbol: '€',
    },
    {
        currencyKey: 31,
        currencyName: 'Azerbaijani Manat',
        currencyCode: 'AZN',
        currencySymbol: 'ман.',
    },
    {
        currencyKey: 32,
        currencyName: 'Argentine Peso',
        currencyCode: 'ARS',
        currencySymbol: '$',
    },
    {
        currencyKey: 36,
        currencyName: 'Australian Dollar',
        currencyCode: 'AUD',
        currencySymbol: '$',
    },
    {
        currencyKey: 48,
        currencyName: 'Bahraini Dinar',
        currencyCode: 'BHD',
        currencySymbol: 'د.ب.‏',
    },
    {
        currencyKey: 50,
        currencyName: 'Bangladeshi Taka',
        currencyCode: 'BDT',
        currencySymbol: '৳',
    },
    {
        currencyKey: 51,
        currencyName: 'Armenian Dram',
        currencyCode: 'AMD',
        currencySymbol: 'դր.',
    },
    {
        currencyKey: 68,
        currencyName: 'Bolivian Boliviano',
        currencyCode: 'BOB',
        currencySymbol: 'Bs',
    },
    {
        currencyKey: 70,
        currencyName: 'Bosnia-Herzegovina Convertible Mark',
        currencyCode: 'BAM',
        currencySymbol: 'KM',
    },
    {
        currencyKey: 72,
        currencyName: 'Botswanan Pula',
        currencyCode: 'BWP',
        currencySymbol: 'P',
    },
    {
        currencyKey: 74,
        currencyName: 'Norwegian Krone',
        currencyCode: 'NOK',
        currencySymbol: 'kr',
    },
    {
        currencyKey: 76,
        currencyName: 'Brazilian Real',
        currencyCode: 'BRL',
        currencySymbol: 'R$',
    },
    {
        currencyKey: 84,
        currencyName: 'Belize Dollar',
        currencyCode: 'BZD',
        currencySymbol: '$',
    },
    {
        currencyKey: 96,
        currencyName: 'Brunei Dollar',
        currencyCode: 'BND',
        currencySymbol: '$',
    },
    {
        currencyKey: 100,
        currencyName: 'Bulgarian Lev',
        currencyCode: 'BGN',
        currencySymbol: 'лв.',
    },
    {
        currencyKey: 108,
        currencyName: 'Burundian Franc',
        currencyCode: 'BIF',
        currencySymbol: 'FBu',
    },
    {
        currencyKey: 112,
        currencyName: 'Belarusian Ruble',
        currencyCode: 'BYR',
        currencySymbol: 'BYR',
    },
    {
        currencyKey: 116,
        currencyName: 'Cambodian Riel',
        currencyCode: 'KHR',
        currencySymbol: '៛',
    },
    {
        currencyKey: 120,
        currencyName: 'CFA Franc BEAC',
        currencyCode: 'XAF',
        currencySymbol: 'FCFA',
    },
    {
        currencyKey: 124,
        currencyName: 'Canadian Dollar',
        currencyCode: 'CAD',
        currencySymbol: '$',
    },
    {
        currencyKey: 132,
        currencyName: 'Cape Verdean Escudo',
        currencyCode: 'CVE',
        currencySymbol: 'CV$',
    },
    {
        currencyKey: 152,
        currencyName: 'Chilean Peso',
        currencyCode: 'CLP',
        currencySymbol: '$',
    },
    {
        currencyKey: 156,
        currencyName: 'Chinese Yuan',
        currencyCode: 'CNY',
        currencySymbol: 'CN¥',
    },
    {
        currencyKey: 170,
        currencyName: 'Colombian Peso',
        currencyCode: 'COP',
        currencySymbol: '$',
    },
    {
        currencyKey: 174,
        currencyName: 'Comorian Franc',
        currencyCode: 'KMF',
        currencySymbol: 'FC',
    },
    {
        currencyKey: 184,
        currencyName: 'New Zealand Dollar',
        currencyCode: 'NZD',
        currencySymbol: '$',
    },
    {
        currencyKey: 188,
        currencyName: 'Costa Rican Colón',
        currencyCode: 'CRC',
        currencySymbol: '₡',
    },
    {
        currencyKey: 191,
        currencyName: 'Croatian Kuna',
        currencyCode: 'HRK',
        currencySymbol: 'kn',
    },
    {
        currencyKey: 204,
        currencyName: 'CFA Franc BCEAO',
        currencyCode: 'XOF',
        currencySymbol: 'CFA',
    },
    {
        currencyKey: 208,
        currencyName: 'Danish Krone',
        currencyCode: 'DKK',
        currencySymbol: 'kr',
    },
    {
        currencyKey: 214,
        currencyName: 'Dominican Peso',
        currencyCode: 'DOP',
        currencySymbol: 'RD$',
    },
    {
        currencyKey: 231,
        currencyName: 'Ethiopian Birr',
        currencyCode: 'ETB',
        currencySymbol: 'Br',
    },
    {
        currencyKey: 232,
        currencyName: 'Eritrean Nakfa',
        currencyCode: 'ERN',
        currencySymbol: 'Nfk',
    },
    {
        currencyKey: 239,
        currencyName: 'British Pound Sterling',
        currencyCode: 'GBP',
        currencySymbol: '£',
    },
    {
        currencyKey: 262,
        currencyName: 'Djiboutian Franc',
        currencyCode: 'DJF',
        currencySymbol: 'Fdj',
    },
    {
        currencyKey: 268,
        currencyName: 'Georgian Lari',
        currencyCode: 'GEL',
        currencySymbol: 'GEL',
    },
    {
        currencyKey: 288,
        currencyName: 'Ghanaian Cedi',
        currencyCode: 'GHS',
        currencySymbol: 'GH₵',
    },
    {
        currencyKey: 320,
        currencyName: 'Guatemalan Quetzal',
        currencyCode: 'GTQ',
        currencySymbol: 'Q',
    },
    {
        currencyKey: 324,
        currencyName: 'Guinean Franc',
        currencyCode: 'GNF',
        currencySymbol: 'FG',
    },
    {
        currencyKey: 340,
        currencyName: 'Honduran Lempira',
        currencyCode: 'HNL',
        currencySymbol: 'L',
    },
    {
        currencyKey: 344,
        currencyName: 'Hong Kong Dollar',
        currencyCode: 'HKD',
        currencySymbol: '$',
    },
    {
        currencyKey: 348,
        currencyName: 'Hungarian Forint',
        currencyCode: 'HUF',
        currencySymbol: 'Ft',
    },
    {
        currencyKey: 352,
        currencyName: 'Icelandic Króna',
        currencyCode: 'ISK',
        currencySymbol: 'kr',
    },
    {
        currencyKey: 356,
        currencyName: 'Indian Rupee',
        currencyCode: 'INR',
        currencySymbol: 'টকা',
    },
    {
        currencyKey: 360,
        currencyName: 'Indonesian Rupiah',
        currencyCode: 'IDR',
        currencySymbol: 'Rp',
    },
    {
        currencyKey: 364,
        currencyName: 'Iranian Rial',
        currencyCode: 'IRR',
        currencySymbol: '﷼',
    },
    {
        currencyKey: 368,
        currencyName: 'Iraqi Dinar',
        currencyCode: 'IQD',
        currencySymbol: 'د.ع.‏',
    },
    {
        currencyKey: 376,
        currencyName: 'Israeli New Sheqel',
        currencyCode: 'ILS',
        currencySymbol: '₪',
    },
    {
        currencyKey: 388,
        currencyName: 'Jamaican Dollar',
        currencyCode: 'JMD',
        currencySymbol: '$',
    },
    {
        currencyKey: 392,
        currencyName: 'Japanese Yen',
        currencyCode: 'JPY',
        currencySymbol: '￥',
    },
    {
        currencyKey: 400,
        currencyName: 'Jordanian Dinar',
        currencyCode: 'JOD',
        currencySymbol: 'د.أ.‏',
    },
    {
        currencyKey: 404,
        currencyName: 'Kenyan Shilling',
        currencyCode: 'KES',
        currencySymbol: 'Ksh',
    },
    {
        currencyKey: 410,
        currencyName: 'South Korean Won',
        currencyCode: 'KRW',
        currencySymbol: '₩',
    },
    {
        currencyKey: 414,
        currencyName: 'Kuwaiti Dinar',
        currencyCode: 'KWD',
        currencySymbol: 'د.ك.‏',
    },
    {
        currencyKey: 422,
        currencyName: 'Lebanese Pound',
        currencyCode: 'LBP',
        currencySymbol: 'ل.ل.‏',
    },
    {
        currencyKey: 438,
        currencyName: 'Swiss Franc',
        currencyCode: 'CHF',
        currencySymbol: 'CHF',
    },
    {
        currencyKey: 446,
        currencyName: 'Macanese Pataca',
        currencyCode: 'MOP',
        currencySymbol: 'MOP$',
    },
    {
        currencyKey: 450,
        currencyName: 'Malagasy Ariary',
        currencyCode: 'MGA',
        currencySymbol: 'MGA',
    },
    {
        currencyKey: 458,
        currencyName: 'Malaysian Ringgit',
        currencyCode: 'MYR',
        currencySymbol: 'RM',
    },
    {
        currencyKey: 480,
        currencyName: 'Mauritian Rupee',
        currencyCode: 'MUR',
        currencySymbol: 'MURs',
    },
    {
        currencyKey: 484,
        currencyName: 'Mexican Peso',
        currencyCode: 'MXN',
        currencySymbol: '$',
    },
    {
        currencyKey: 498,
        currencyName: 'Moldovan Leu',
        currencyCode: 'MDL',
        currencySymbol: 'MDL',
    },
    {
        currencyKey: 504,
        currencyName: 'Moroccan Dirham',
        currencyCode: 'MAD',
        currencySymbol: 'د.م.‏',
    },
    {
        currencyKey: 508,
        currencyName: 'Mozambican Metical',
        currencyCode: 'MZN',
        currencySymbol: 'MTn',
    },
    {
        currencyKey: 512,
        currencyName: 'Omani Rial',
        currencyCode: 'OMR',
        currencySymbol: 'ر.ع.‏',
    },
    {
        currencyKey: 516,
        currencyName: 'Namibian Dollar',
        currencyCode: 'NAD',
        currencySymbol: 'N$',
    },
    {
        currencyKey: 524,
        currencyName: 'Nepalese Rupee',
        currencyCode: 'NPR',
        currencySymbol: 'नेरू',
    },
    {
        currencyKey: 558,
        currencyName: 'Nicaraguan Córdoba',
        currencyCode: 'NIO',
        currencySymbol: 'C$',
    },
    {
        currencyKey: 566,
        currencyName: 'Nigerian Naira',
        currencyCode: 'NGN',
        currencySymbol: '₦',
    },
    {
        currencyKey: 586,
        currencyName: 'Pakistani Rupee',
        currencyCode: 'PKR',
        currencySymbol: '₨',
    },
    {
        currencyKey: 591,
        currencyName: 'Panamanian Balboa',
        currencyCode: 'PAB',
        currencySymbol: 'B/.',
    },
    {
        currencyKey: 600,
        currencyName: 'Paraguayan Guarani',
        currencyCode: 'PYG',
        currencySymbol: '₲',
    },
    {
        currencyKey: 604,
        currencyName: 'Peruvian Nuevo Sol',
        currencyCode: 'PEN',
        currencySymbol: 'S/.',
    },
    {
        currencyKey: 608,
        currencyName: 'Philippine Peso',
        currencyCode: 'PHP',
        currencySymbol: '₱',
    },
    {
        currencyKey: 616,
        currencyName: 'Polish Zloty',
        currencyCode: 'PLN',
        currencySymbol: 'zł',
    },
    {
        currencyKey: 634,
        currencyName: 'Qatari Rial',
        currencyCode: 'QAR',
        currencySymbol: 'ر.ق.‏',
    },
    {
        currencyKey: 642,
        currencyName: 'Romanian Leu',
        currencyCode: 'RON',
        currencySymbol: 'RON',
    },
    {
        currencyKey: 646,
        currencyName: 'Rwandan Franc',
        currencyCode: 'RWF',
        currencySymbol: 'FR',
    },
    {
        currencyKey: 682,
        currencyName: 'Saudi Riyal',
        currencyCode: 'SAR',
        currencySymbol: 'ر.س.‏',
    },
    {
        currencyKey: 702,
        currencyName: 'Singapore Dollar',
        currencyCode: 'SGD',
        currencySymbol: '$',
    },
    {
        currencyKey: 704,
        currencyName: 'Vietnamese Dong',
        currencyCode: 'VND',
        currencySymbol: '₫',
    },
    {
        currencyKey: 706,
        currencyName: 'Somali Shilling',
        currencyCode: 'SOS',
        currencySymbol: 'Ssh',
    },
    {
        currencyKey: 710,
        currencyName: 'South African Rand',
        currencyCode: 'ZAR',
        currencySymbol: 'R',
    },
    {
        currencyKey: 729,
        currencyName: 'Sudanese Pound',
        currencyCode: 'SDG',
        currencySymbol: 'SDG',
    },
    {
        currencyKey: 752,
        currencyName: 'Swedish Krona',
        currencyCode: 'SEK',
        currencySymbol: 'kr',
    },
    {
        currencyKey: 760,
        currencyName: 'Syrian Pound',
        currencyCode: 'SYP',
        currencySymbol: 'ل.س.‏',
    },
    {
        currencyKey: 764,
        currencyName: 'Thai Baht',
        currencyCode: 'THB',
        currencySymbol: '฿',
    },
    {
        currencyKey: 776,
        currencyName: 'Tongan Pa?anga',
        currencyCode: 'TOP',
        currencySymbol: 'T$',
    },
    {
        currencyKey: 780,
        currencyName: 'Trinidad and Tobago Dollar',
        currencyCode: 'TTD',
        currencySymbol: '$',
    },
    {
        currencyKey: 784,
        currencyName: 'United Arab Emirates Dirham',
        currencyCode: 'AED',
        currencySymbol: 'د.إ.‏',
    },
    {
        currencyKey: 788,
        currencyName: 'Tunisian Dinar',
        currencyCode: 'TND',
        currencySymbol: 'د.ت.‏',
    },
    {
        currencyKey: 792,
        currencyName: 'Turkish Lira',
        currencyCode: 'TRY',
        currencySymbol: 'TL',
    },
    {
        currencyKey: 800,
        currencyName: 'Ugandan Shilling',
        currencyCode: 'UGX',
        currencySymbol: 'USh',
    },
    {
        currencyKey: 804,
        currencyName: 'Ukrainian Hryvnia',
        currencyCode: 'UAH',
        currencySymbol: '₴',
    },
    {
        currencyKey: 818,
        currencyName: 'Egyptian Pound',
        currencyCode: 'EGP',
        currencySymbol: 'ج.م.‏',
    },
    {
        currencyKey: 834,
        currencyName: 'Tanzanian Shilling',
        currencyCode: 'TZS',
        currencySymbol: 'TSh',
    },
    {
        currencyKey: 858,
        currencyName: 'Uruguayan Peso',
        currencyCode: 'UYU',
        currencySymbol: '$',
    },
    {
        currencyKey: 860,
        currencyName: 'Uzbekistan Som',
        currencyCode: 'UZS',
        currencySymbol: 'UZS',
    },
    {
        currencyKey: 862,
        currencyName: 'Venezuelan Bolívar',
        currencyCode: 'VEF',
        currencySymbol: 'Bs.F.',
    },
    {
        currencyKey: 887,
        currencyName: 'Yemeni Rial',
        currencyCode: 'YER',
        currencySymbol: 'ر.ي.‏',
    },
];

export default currencies;
